version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - 4444:4444

    command: npm run start:dev

    depends_on:
      - postgres

    restart: always

  postgres: 
    container_name: postgres

    image: postgres:12

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task3

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin: 
    container_name: pgadmin

    image: dpage/pgadmin4

    environment: 
      - PGADMIN_DEFAULT_EMAIL=vitmar170408@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY=False

    ports: 
      - "5050:80"

    volumes:
      - pgadmin-data:/ var/lib/pgadmin

volumes: 
  pgdata:
  pgadmin-data:


